## Best model - 2 models color / grayscale with occlusion weighted MSE loss function
(The result varies from 0.00089 to 0.0025 for 30 epochs training)

In [9]:
# Data manipulation and utilities
import os
import pickle
import pandas as pd
import numpy as np
from collections import OrderedDict
from tqdm import tqdm

# Image processing
from PIL import Image
import cv2
import matplotlib.pyplot as plt

# PyTorch and torchvision
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision
import torchvision.transforms as transforms
from torchvision import models
from torchvision.models import mobilenet_v3_small

# Scikit-learn tools
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

from functions_modelization import *

In [6]:
df_train = pd.read_csv("df_train.csv")
df_test = pd.read_csv("df_test.csv")

image_dir = "Data/crops_100K"

df_train = df_train.dropna()
df_test = df_test.dropna()
df_train.tail()

,filename,FaceOcclusion,gender,initial_index,gender_id,db_number,count,color,image_width,image_height,...,pixels,pixels_mean,pixels_mean_R,pixels_mean_G,pixels_mean_B,pixels_std,pixels_std_R,pixels_std_G,pixels_std_B,no_color
101340,database3/database3/m.01drbr/85-FaceId-0_align...,0.017,1.000,101340,1,3,1,1,224,224,...,50176,74.146418,96.856525,65.668367,59.914361,52.118925,57.765103,46.664056,42.949133,0
101341,database3/database3/m.01drbr/86-FaceId-0_align...,0.152,1.000,101341,1,3,1,1,224,224,...,50176,105.734807,132.088728,98.936523,86.179169,46.897575,45.496415,42.261974,40.236558,0
101342,database3/database3/m.01drbr/87-FaceId-0_align...,0.004,0.999,101342,1,3,1,1,224,224,...,50176,117.631304,134.155991,114.254125,104.483797,85.209480,78.525353,84.753668,89.304108,0
101343,database3/database3/m.01drbr/90-FaceId-0_align...,0.012,1.000,101343,1,3,1,1,224,224,...,50176,101.296530,135.023378,91.619699,77.246512,85.260812,74.632720,82.913992,86.913179,0
101344,database3/database3/m.01drbr/92-FaceId-0_align...,0.036,1.000,101344,1,3,1,1,224,224,...,50176,42.016037,50.332529,40.127591,35.587990,40.702440,46.160917,38.629777,35.113045,0

In [7]:
df_test.tail()

,filename,gender,FaceOcclusion,initial_index,gender_id,db_number,count,color,image_width,image_height,...,pixels,pixels_mean,pixels_mean_R,pixels_mean_G,pixels_mean_B,pixels_std,pixels_std_R,pixels_std_G,pixels_std_B,no_color
30502,database3/database3/m.01507p/85-FaceId-0_align...,-1.0,-1.0,30502,-1,3,1,1,224,224,...,50176,108.125412,133.719846,105.923948,84.732442,67.730923,76.965272,60.439317,54.577625,0
30503,database3/database3/m.01507p/86-FaceId-0_align...,-1.0,-1.0,30503,-1,3,1,1,224,224,...,50176,112.183687,148.427415,107.474251,80.649394,64.772321,58.861269,57.799678,58.742751,0
30504,database3/database3/m.01507p/87-FaceId-0_align...,-1.0,-1.0,30504,-1,3,1,1,224,224,...,50176,67.579673,82.065071,63.406948,57.267000,67.723229,81.012541,62.100222,54.829264,0
30505,database3/database3/m.01507p/88-FaceId-0_align...,-1.0,-1.0,30505,-1,3,1,1,224,224,...,50176,144.013665,175.908662,141.011061,115.121273,65.504749,55.911215,58.060830,67.189403,0
30506,database3/database3/m.01507p/89-FaceId-0_align...,-1.0,-1.0,30506,-1,3,1,1,224,224,...,50176,138.909817,182.969667,131.055485,102.704301,55.479070,53.719294,42.137254,35.477747,0

# 1 Data exploration

In [31]:
# Prediction
results_list = []
for batch_idx, (X, is_gray, filename) in tqdm(enumerate(test_loader), total=len(test_loader)):
    X = X.to(device)
    for i in range(len(X)):  
        if is_gray[i].item():  # Test if the image is grayscale image
            y_pred = model_gray(X[i].unsqueeze(0)) 
        else:
            y_pred = model_color(X[i].unsqueeze(0)) 
        
        results_list.append({'pred': float(y_pred.squeeze().item())})

test_df = pd.DataFrame(results_list)
test_df.head()

100%|██████████| 3814/3814 [02:03<00:00, 30.86it/s]

       pred
0  0.307591
1  0.355882
2  0.119028
3  0.309866
4  0.405662

In [32]:
test_df.to_csv("Data_Challenge.csv", header = None, index = None)